package com.herbalapp

object HerbalsData {
	private val herbalNames = arrayOf("Kunyit",
		"Jeruk Nipis",
		"Kayu Manis",
		"Lemon",
		"Madu",
		"Daun Kelor",
		"Daun Mint",
		"Kencur",
		"Temulawak",
		"Chamomile")
	
	private val herbalDetails = arrayOf("Kandungan kunyit \n \n   Menurut buku Health Secret of Turmeric (Kunyit) yang ditulis oleh Pangkalan Ide (2011), kunyit mengandung kurkumin, yaitu suatu zat antibakteri yang dapat merangsang dinding kantong empedu untuk berkontraksi mengeluarkan empedu sehingga pencernaan lebih semputna. Selain itu, kunyit juga mengandung minyak atsiri yang berkhasiat mencegah keluarnya asam lambung berlebih dan mengurangi peristaltik usus yang terlalu kuat. Rimpang kunyit juga mengandung zat lain, seperti minyak volatil, kurkumin, damar, gom, pati, lemak, protein kalsium, fosfor, besi, hingga vitamin C.\n   \n   Salah satu cara mengonsumsi kunyit adalah menjadikannya minuman kunyit asam. Untuk membuatnya, kita bisa mengolahnya bersama asam jawa, gula kelapa, dan air.",
		"    Mengonsumsi air dari perasan buah jeruk nipis memiliki berbagai manfaat untuk kesehatan tubuh. Jeruk nipis sering dinikmati oleh masyarakat dengan cara mencampurkannya ke dalam air putih, menjadi minuman pelepas dahaga yang menyehatkan.\n \n   Dilansir dari Healthline, jeruk nipis merupakan sumber antioksidan yang sangat baik yang bisa berguna melindungi tubuh dari radikal bebas. Selain itu, mengonsumsi air perasan buah tersebut juga dapat meningkatkan kesehatan dan meremajakan kulit.\n   Terdapat kandungan nutrisi penting di dalam jeruk nipis, seperti: Kalium, Vitamin A, Vitamin B, Vitamin C, Vitamin D, Kalsium, dan Magnesium.\n   Berikut ini adalah manfaat yang bisa didapat ketika Anda menambahkan perasan air jeruk nipis ke dalam air putih untuk dikonsumsi:\n   1. Meremajakan kulit Jeruk nipis mengandung vitamin C dan flavonoid yang merupakan antioksidan untuk memperkuat kolagen. Minum air jerus nipis juga dapat menghidrasi tubuh dan meremajakan kulit. Namun tidak disarankan untuk mengoleskan air jeruk nipis langsung ke kulit Anda.\n   2. Meningkatkan pencernaan Perasan air jeruk nipis bersifat asam, sehingga dapat membantu air liur memecah makanan untuk pencernaan menjadi lebih baik. Selain itu, kandungan flavonoid dalam jeruk nipis dapat merangsang sekresi cairan pencernaan ",
		"    Kayu manis merupakan rempah yang dibuat dari kulit bagian dalam pohon yang secara ilmiah dikenal dengan nama Cinnamomum. Aroma dan rasa kayu manis yang khas berasal dari bagian yang berminyak sangat tinggi dalam senyawa cinnamaldehyde.\n \n   Para ilmuwan percaya bahwa cinnamaldehyde adalah senyawa yang bertanggungjawab atas manfaat kesehatan dari kayu manis. Kayu manis memiliki banyak manfaat kesehatan, mulai dari mengatasi gangguan kesehatan ringan hingga mencegah penyakit kronis.\n  Selengkapnya, berikut adalah manfaat kayu manis untuk kesehatan, dilansir dari Healthline, 5 Juli 2018.\n   1. Melawan infeksi bakteri dan jamur Cinnamaldehyde mampu membantu melawan berbagai jenis bakteri. Selain itu, minyak kayu manis juga terbukti efektif untuk mengatasi infeksi akibat jamur. Efek antimikroba yang dimiliki kayu manis dapat membantu mencegah kerusakan gigi dan mengurangi bau mulut.\n   2. Melindungi dari penyakit kanker Kayu manis telah banyak dipelajari untuk potensi penggunaannya dalam mencegah dan mengobati penyakit kanker. Bukti terbatas pada penelitian tabung dan hewan memperlihatkan bahwa ekstrak kayu manis dapat melindungi dari kanker. Kayu manis berpotensi mencegah kanker dengan mengurangi pertumbuhan sel kanker dan pembentukan pembuluh darah di tumor.",
		"    Air rebusan lemon bisa digunakan menaikkan sistem imun, menurunkan berat badan dan mempercantik kulit.\n   Dilansir dari Medical News Today, beberapa ilmuwan yang sudah melakukan berbagai penelitian meyakini akan khasiat air rebusan lemon ini. Namun beberapa lagi justru menyangsikan karena proses perebusan lemon dinilai bisa mengurangi kadar vitamin dan nutrisi yang ada di dalamnya. Meski begitu, peneliti tak meniadakan sama sekali kandungan nutrisi yang ada pada lemon meski lemon sudah melalui proses pemanasan. Dalam menakar manfaat air rebusan lemon, peneliti memadukan manfaat dari lemon dan manfaat dari segelas air hangat.\n   Berikut ini adalah beberapa manfaat dari air rebusan lemon yang diyakini oleh para ilmuwan dan ahli nutrisi:\n   1. Menyehatkan kulit\n   Lemon mengandung vitamin C dan antioksidan yang bisa melindungi kerusakan sel-sel pada kulit, mencegah timbulnya efek penuaan dini. Beberapa peneliti juga menyatakan bahwa mengonsumsi vitamin C alami seperti yang ada pada lemon bisa menyembuhkan berbagai peradangan pada kulit dan mencegah keriput dan garis-garis halus agar tak datang terlalu awal.\n   2. Menurunkan tekanan darah\n   Kalsium dan potassium pada lemon terbukti bisa efektif menurunkan tekanan darah. Ahli nutrisi menyarankan untuk mengonsumsi mineral ini dari bahan pangan alami seperti lemon daripada melalui kemasan suplemen.\n   3. Menaikkan sistem imun\n Vitamin C alami pada lemon juga bisa menaikkan sistem imun dan melindungi tubuh dari infeksi saluran pernapasan. Dalam penelitian tahun 2017 didapatkan bahwa vitamin C dalam dosis besar dalam lemon bisa efektif mengobati pneumonia.",
		"    Madu adalah salah satu makanan yang sering dikaitkan dengan berbagai manfaat kesehatan. Dalam berbagai budaya selama berabad-abad, cairan manis ini telah digunakan dalam banyak keperluan pengobatan. Salah satu yang paling dikenal adalah penggunaan madu dalam pengobatan Ayurveda sela sebagai obat pencernaan dan ketidakseimbangan pada tubuh.\n Sebuah temuan yang dipublikasikan dalam Iranian Journal of Basic Medical Sciences tahun 2013 juga menunjukkan bahwa madu telah digunakan oleh manusia sejak 8.000 tahun lalu.\n Hingga masa kini pun, madu masih dipercaya punya banyak manfaat untuk tubuh. Tapi, apa saja manfaat dari madu yang sudah terbukti secara ilmiah?\n   1. Energy booster\n   Madu merupakan cairan kental manis yang dibuat oleh lebah. Lebah mengumpulkan gula dari nektar bunga di lingkungannya. Produk akhirnya adalah madu, yaitu cairan yang berfungsi sebagai cadangan makanan untuk lebah. Merangkum dari Healthline, secara nutrisi, satu sendok makan madu mengandung 64 kalori dan 17 gram gula termasuk fruktosa, glukosa, maltosa, dan sukrosa. Kandungan tersebut membuat madu menjadi sumber energi yang baik.\n   2. Mengobati batuk\n   Sebuah studi tahun 2012 yang terbit dalam Journal Pediatrics menemukan bahwa konsumsi dua sendok teh madu bisa membantu menyembuhkan batuk yang membandel. Hal ini diketahui karena sifat anti-mikroba dalam madu yang bisa membunuh bakteri tertentu. Penelitian lain yang melibatkan 139 anak menemukan bahwa madu dapat meredakan batuk di malam hari dan meningkatkan kualitas tidur dibanding obat batuk anak. Merangkum dari CNN, penelitian lain di Italia dan Israel juga menunjukkan hasil serupa meski menggunakan jenis madu yang berbeda.",
		"    Daun kelor adalah tanaman dengan nama latin Moringa oleifera atau dikenal juga sebagai daun moringa. Tanaman ini telah dipuji karena khasiatnya yang telah diketahui sejak ribuan tahun lalu.\n   Dikenal sebagai superfood, seperti dikutip dari Healthline, Sabtu (30/4/2022), sejauh ini para ilmuwan hanya menyelidiki sebagian kecil dari banyaknya manfaat kesehatan dari daun kelor.\n   Berikut ini segudang manfaat daun kelor berdasarkan sains yang didukung oleh bukti ilmiah dari penelitian yang telah dipublikasikan di jurnal PubMed.\n  1. Manfaat gizi dan nutrisi dalam daun kelor\n   Moringa oleifera atau daun kelor adalah pohon asli yang berasal dari India Utara. Pohon kelor memiliki berbagai nama, seperti pohon paha, pohon lobak atau pohon minyak ben. Hampir semua bagian pohon kelor dapat dikonsumsi atau dimanfaatkan sebagai bahan obat-obatan herbal tradisional. Baik daun kelor maupun bijinya biasa dimakan oleh masyarakat di India dan Afrika.\n   2. Manfaat daun kelor penangkal radikal bebas\n   Manfaat daun kelor untuk kesehatan yakni sebagai penangkal radikal bebas karena kandungan antioksidan yang tinggi dalam tanaman ini.\n   Antioksidan adalah senyawa yang bertindak melawan radikal bebas dalam tubuh Anda. ",
		"    Manfaat daun mint tak sekadar sebagai penyegar napas atau menambah rasa makanan dan minuman, tetapi juga berkhasiat bagi kesehatan.\n   Manfaat daun mint untuk kesehatan bisa didapatkan dengan berbagai cara, seperti menambahkannya sebagai rasa pada minuman atau menu makanan seperti sup, salad, atau menu ayam.\n   Beberapa manfaat daun mint untuk kesehatan antara lain:\n   1. Meredakan gejala flu\n   Mentol juga bisa melonggarkan lendir sehingga lebih mudah untuk dikeluarkan. Mengoleskan salep mentol atau gosok uap bisa menjadi pilihan perawatan yang aman dan efektif untuk anak-anak yang menderita flu biasa. Asosiasi Paru-paru Amerika (ALA) menyebutkan belum ada studi ilmiah yang mendukung penggunaan mentol untuk mengatasi gejala pilek. Meskipun demikian, beberapa orang mungkin menemukan bahwa gejala pilek berkurang setelah menggosokkan mentol.\n   2. Mendukung kesehatan Otak\n Manfaat mint untuk kesehatan lainnya adalah meningkatkan kesehatan otak.\n   Menurut WebMD, sebuah studi menemukan ekstrak mint memiliki potensi untuk mengobati gejala Alzheimer. Namun, penelitian lebih lanjut dibutuhkan untuk mengonfirmasi temuan ini.\n   Studi lain menemukan bahwa mencium peppermint dapat meningkatkan memori dan meningkatkan kewaspadaan, meskipun tidak diketahui apakah menelannya memiliki efek yang sama. ",
		"    Dalam rimpang kencur terkandung berbagai senyawa kimia yang penting sebagai obat herbal.\n   Kandungan senyawa itu di antaranya berupa unsur mineral 13,73 persen, zat tepung atau pati 4,14 persen, dan minyak atsiri sekitar 0,02 persen.\n   Senyawa dalam minyak atsiri kencur bahkan ada cukup banyak, seperti asam metil kanil dan penta dekaan, asam sinamat, asam anisat, sineol, etil ester, paraeumorin, borneol, kamphene, gom, dan unsur alkaloid.\n   Tak hanya itu, ekstrak kencur juga dapat memberikan efek antiinflamasi, antioksidan, dan bersifat analgesik (pereda nyeri). Banyaknya senyawa aktif atau bahan yang dikandung, membuat kencur kaya akan manfaat kesehatan.\n   Melansir berbagai sumber, berikut ini adalah ragam manfaat kencur untuk kesehatan:\n   1. Mencegah kanker\n   Merangkum Buku 56 Makanan Ajaib dan Manfaatnya untuk Kesehatan dan Kecantikan (2018) oleh Yusuf CK Arianto, rimpang kencur juga mengandung etil p-metoksisinamat yang mampu menghambat proliferasi sel karsinoma hati hepatoseluler yang berguna sebagai antikanker.\n   Aroma kencur yang berasal dari kandungan etil p-metoksisinamat dan etil cinnamate juga dapat memberikan efek menenangkan.\n   2. Mengobati penyakit akibat bakteri\n Ekstrak methanol dari kencur sangat efektir dalam menangkal dan mengatasi bakteri, termasuk bakteri penyebab penyakit sistem saraf pusat yang dinamakan granulomatous amoebic encephalitis.\n   Kencur juga mampu membunuh amoebic keratitis, bakteri penyebab infeksi pada kornea mata, maupun dalam mengatasi cacing parasite penyebab penyakit toksokariasis. ",
		"    Menurut buku Tanaman Potensial Berkhasiat Obat (2020) yang ditulis oleh Dr Suharman, SP, MSi, temulawak mengandung zat warna alami yaitu kurkuminoid yang terdiri dari warna kuning hingga merah jingga. Zat warna ini banyak dimanfaatkan sebagai pewarna makanan dan minuman serta bahan kosmetik. Kurkuminoid juga bisa digunakan sebagai anti bakteri dan anti virus sebagai bahan obat herbal.\n   Zat warna ini dihasilkan dari rimpang temulawak yang telah dicuci, diiris, dikeringkan, kemudian digiling sampai halus hingga menjadi bubuk.\n   Bubuk ini kemudian diekstraksi dan diolah untuk menjadi produk berupa benzol dan kurkuminoid.\n   1. Sumber Antioksidan yang baik\n   2. Menambah nafau makan\n   3. Meningkatkan daya tahan tubuh ",
		"    Kamomil atau bunga tanaman chamomile sejak lama dimanfaatkan untuk membantu mengatasi susah tidur.\n   Sehingga, beberapa orang beralih minum chamomile dan beberapa teh herbal bebas kafein lainnya.\n   Sebelum mengetahui cara mengatasi susah tidur dengan chamomile, kenali dulu studi manfaat sampai cara kerja bahan alami ini untuk membantu mengatasi susah tidur.\n   Melansir Sleep Foundation, chamomile mengandung beberapa senyawa kimia jenis apigenin. Ketika membentuk ikatan bersama reseptor benzodiazepin di otak, senyawa ini dapat membantu pikiran tetap rileks dan menyiapkan tubuh untuk beristirahat.\n   Beberapa studi membuktikan, manfaat chamomile terbukti membantu mengatasi susah tidur. Sebuah penelitian terhadap ibu yang baru melahirkan, wanita yang minum seduhan chamomile cenderung tidak merasakan susah tidur dan gejala depresi pasca-persalinan berkurang.\n   Selain itu mengkonsumsi Chamomile juga bisa menjaga kesehatan pencernaan. ")
	
	private val herbalsImages = intArrayOf(R.drawable.kunyit,
		R.drawable.jeruk_nipis,
		R.drawable.kayu_manis,
		R.drawable.lemon,
		R.drawable.madu,
		R.drawable.kelor,
		R.drawable.mint,
		R.drawable.kencur,
		R.drawable.temulawak,
		R.drawable.chamomile)
	
	val listData: ArrayList<Herbal>
		get() {
			val list = arrayListOf<Herbal>()
			for (position in herbalNames.indices) {
				val herbal = Herbal()
				herbal.name = herbalNames[position]
				herbal.detail = herbalDetails[position]
				herbal.photo = herbalsImages[position]
				list.add(herbal)
			}
			return list
		}
	
}